# Generated by Django 4.2.24 on 2025-11-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_order_supplier_acknowledged_order_supplier_eta_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["organization", "status", "-created_at"],
                name="order_org_status_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["supplier", "status"], name="order_supplier_status_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status", "-created_at"], name="order_status_created_idx"),
        ),
    ]
