# Generated by Django 4.2.24 on 2025-11-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="actual_delivery_date",
            field=models.DateField(blank=True, help_text="Gerçek teslimat tarihi", null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="estimated_delivery_date",
            field=models.DateField(
                blank=True,
                help_text="Owner tarafından belirlenen tahmini teslimat tarihi",
                null=True,
            ),
        ),
    ]
