# Generated by Django 4.2.24 on 2025-11-15 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_add_metrics_and_scoring_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="feedback_token",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
