# Generated by Django 4.2.24 on 2025-11-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_supplier_multi_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorysupplierrule',
            name='field_operator',
            field=models.CharField(blank=True, choices=[('eq', '='), ('neq', '!='), ('gt', '>'), ('gte', '>='), ('lt', '<'), ('lte', '<='), ('contains', 'içerir'), ('in', 'şunlardan biri (virgülle ayırın)')], max_length=20),
        ),
    ]
