# Generated by Django 4.2.24 on 2025-11-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_ticket_supplier_token_ticketemailreply"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="is_simplified",
            field=models.BooleanField(default=False, verbose_name="Basit Usul"),
        ),
    ]
