# Generated by Django 4.2.24 on 2025-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_supplier_is_simplified"),
    ]

    operations = [
        migrations.AddField(
            model_name="ownerquoteadjustment",
            name="is_selected",
            field=models.BooleanField(default=True, verbose_name="Müşteriye Gönder"),
        ),
    ]
