# Generated by Django 4.2.24 on 2025-11-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_ownerquoteadjustment_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='is_simplified',
            field=models.BooleanField(default=True, verbose_name='Basit Usul'),
        ),
    ]
