# Generated by Django 4.2.24 on 2025-11-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_change_supplier_is_simplified_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quoteitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
