# Generated by Django 4.2.24 on 2025-11-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_change_quoteitem_unit_price_decimals"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(
                fields=["supplier", "-created_at"], name="quote_supplier_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quote",
            index=models.Index(fields=["ticket", "-created_at"], name="quote_ticket_created_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["organization", "status", "-created_at"], name="ticket_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["customer", "status"], name="ticket_customer_status_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["category", "status"], name="ticket_category_status_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["status", "-created_at"], name="ticket_status_created_idx"),
        ),
    ]
