# Generated by Django 4.2.24 on 2025-11-15 08:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_add_organization_email_settings"),
        ("billing", "0007_add_metrics_and_scoring_system"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0025_add_performance_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "total_quotes_sent",
                    models.IntegerField(default=0, verbose_name="Toplam Gönderilen Teklif"),
                ),
                (
                    "total_quotes_accepted",
                    models.IntegerField(default=0, verbose_name="Kabul Edilen Teklif"),
                ),
                (
                    "win_rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Kazanma Oranı %",
                    ),
                ),
                (
                    "avg_quote_response_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Ort. Teklif Süresi (saat)",
                    ),
                ),
                ("total_orders", models.IntegerField(default=0, verbose_name="Toplam Sipariş")),
                (
                    "completed_orders",
                    models.IntegerField(default=0, verbose_name="Tamamlanan Sipariş"),
                ),
                (
                    "on_time_deliveries",
                    models.IntegerField(default=0, verbose_name="Zamanında Teslimat"),
                ),
                (
                    "on_time_delivery_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Zamanında Teslimat %",
                    ),
                ),
                (
                    "avg_product_quality",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        verbose_name="Ort. Ürün Kalitesi",
                    ),
                ),
                (
                    "avg_communication",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        verbose_name="Ort. İletişim",
                    ),
                ),
                (
                    "avg_delivery_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        verbose_name="Ort. Teslimat Puanı",
                    ),
                ),
                (
                    "avg_overall_satisfaction",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        verbose_name="Ort. Genel Memnuniyet",
                    ),
                ),
                (
                    "total_feedback_count",
                    models.IntegerField(default=0, verbose_name="Toplam Anket Sayısı"),
                ),
                (
                    "avg_owner_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        verbose_name="Ort. Owner Değerlendirmesi",
                    ),
                ),
                (
                    "owner_review_count",
                    models.IntegerField(default=0, verbose_name="Owner Değerlendirme Sayısı"),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Genel Skor (100 üzerinden)",
                    ),
                ),
                (
                    "last_calculated",
                    models.DateTimeField(auto_now=True, verbose_name="Son Hesaplama"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_metrics",
                        to="accounts.organization",
                    ),
                ),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="core.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tedarikçi Metrikleri",
                "verbose_name_plural": "Tedarikçi Metrikleri",
                "ordering": ["-overall_score"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-overall_score"],
                        name="core_suppli_organiz_f2862e_idx",
                    ),
                    models.Index(fields=["-overall_score"], name="core_suppli_overall_626343_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OwnerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Yıldız"),
                            (2, "2 Yıldız"),
                            (3, "3 Yıldız"),
                            (4, "4 Yıldız"),
                            (5, "5 Yıldız"),
                        ],
                        verbose_name="Puan",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("reliability", "Güvenilirlik"),
                            ("communication", "İletişim"),
                            ("quality", "Kalite"),
                            ("payment", "Ödeme"),
                            ("pricing", "Fiyatlama"),
                            ("other", "Diğer"),
                        ],
                        max_length=50,
                        verbose_name="Kategori",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Yorum")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_reviews",
                        to="core.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_reviews",
                        to="accounts.organization",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_reviews",
                        to="core.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Owner Değerlendirmesi",
                "verbose_name_plural": "Owner Değerlendirmeleri",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["supplier", "-created_at"], name="core_ownerr_supplie_b3cc66_idx"
                    ),
                    models.Index(
                        fields=["customer", "-created_at"], name="core_ownerr_custome_2edb9f_idx"
                    ),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="core_ownerr_organiz_397459_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "total_tickets_created",
                    models.IntegerField(default=0, verbose_name="Toplam Talep"),
                ),
                (
                    "total_orders_placed",
                    models.IntegerField(default=0, verbose_name="Verilen Sipariş"),
                ),
                (
                    "conversion_rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Dönüşüm Oranı %",
                    ),
                ),
                (
                    "avg_response_time_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Ort. Yanıt Süresi (saat)",
                    ),
                ),
                (
                    "cancelled_orders",
                    models.IntegerField(default=0, verbose_name="İptal Edilen Sipariş"),
                ),
                (
                    "cancellation_rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="İptal Oranı %",
                    ),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=15,
                        verbose_name="Toplam Harcama",
                    ),
                ),
                (
                    "avg_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Ort. Sipariş Değeri",
                    ),
                ),
                (
                    "avg_owner_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        verbose_name="Ort. Owner Değerlendirmesi",
                    ),
                ),
                (
                    "owner_review_count",
                    models.IntegerField(default=0, verbose_name="Owner Değerlendirme Sayısı"),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Genel Skor (100 üzerinden)",
                    ),
                ),
                (
                    "last_calculated",
                    models.DateTimeField(auto_now=True, verbose_name="Son Hesaplama"),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="core.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_metrics",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Müşteri Metrikleri",
                "verbose_name_plural": "Müşteri Metrikleri",
                "ordering": ["-overall_score"],
                "indexes": [
                    models.Index(
                        fields=["organization", "-overall_score"],
                        name="core_custom_organiz_2d0f74_idx",
                    ),
                    models.Index(fields=["-overall_score"], name="core_custom_overall_1d95f5_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "product_quality",
                    models.IntegerField(
                        choices=[
                            (1, "1 Yıldız"),
                            (2, "2 Yıldız"),
                            (3, "3 Yıldız"),
                            (4, "4 Yıldız"),
                            (5, "5 Yıldız"),
                        ],
                        verbose_name="Ürün Kalitesi",
                    ),
                ),
                (
                    "communication",
                    models.IntegerField(
                        choices=[
                            (1, "1 Yıldız"),
                            (2, "2 Yıldız"),
                            (3, "3 Yıldız"),
                            (4, "4 Yıldız"),
                            (5, "5 Yıldız"),
                        ],
                        verbose_name="İletişim Kalitesi",
                    ),
                ),
                (
                    "delivery_time",
                    models.IntegerField(
                        choices=[
                            (1, "1 Yıldız"),
                            (2, "2 Yıldız"),
                            (3, "3 Yıldız"),
                            (4, "4 Yıldız"),
                            (5, "5 Yıldız"),
                        ],
                        verbose_name="Teslimat Süresi",
                    ),
                ),
                (
                    "overall_satisfaction",
                    models.IntegerField(
                        choices=[
                            (1, "1 Yıldız"),
                            (2, "2 Yıldız"),
                            (3, "3 Yıldız"),
                            (4, "4 Yıldız"),
                            (5, "5 Yıldız"),
                        ],
                        verbose_name="Genel Memnuniyet",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Yorumunuz")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks_given",
                        to="core.customer",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_feedback",
                        to="billing.order",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_feedbacks",
                        to="accounts.organization",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_feedbacks",
                        to="core.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Müşteri Geri Bildirimi",
                "verbose_name_plural": "Müşteri Geri Bildirimleri",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["supplier", "-created_at"], name="core_custom_supplie_eb8874_idx"
                    ),
                    models.Index(
                        fields=["customer", "-created_at"], name="core_custom_custome_84e050_idx"
                    ),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="core_custom_organiz_3d08ee_idx",
                    ),
                ],
            },
        ),
    ]
