# Generated by Django 4.2.24 on 2026-01-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_alter_categoryformfield_field_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierproduct",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Boş bırakılırsa tüm müşterilere görünür (Genel ürün)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="core.customer",
            ),
        ),
    ]
