# Generated by Django 4.2.24 on 2026-01-05 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_custom_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0029_add_order_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="organization",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="accounts.organization",
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
