# Generated by Django 4.2.24 on 2025-11-15 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_add_organization_email_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("tokens_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("function_call", models.JSONField(blank=True, null=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai_assistant.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmbeddedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("ticket", "Ticket"),
                            ("quote", "Quote"),
                            ("supplier", "Supplier"),
                            ("comment", "Comment"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.IntegerField()),
                ("content", models.TextField()),
                ("embedding", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedded_docs",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("ticket_update", "Ticket Update"),
                            ("ticket_create", "Ticket Create"),
                            ("quote_request", "Quote Request"),
                            ("email_send", "Email Send"),
                            ("category_create", "Category Create"),
                            ("supplier_update", "Supplier Update"),
                            ("data_query", "Data Query"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField()),
                ("output_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="ai_assistant.message",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_actions",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"], name="ai_assistan_convers_8f1a44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="embeddeddocument",
            index=models.Index(
                fields=["organization", "content_type"], name="ai_assistan_organiz_26a813_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="embeddeddocument",
            index=models.Index(
                fields=["content_type", "object_id"], name="ai_assistan_content_c75a36_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="embeddeddocument",
            unique_together={("organization", "content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["organization", "-updated_at"], name="ai_assistan_organiz_4a8a0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "-updated_at"], name="ai_assistan_user_id_024ca4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiaction",
            index=models.Index(
                fields=["organization", "-created_at"], name="ai_assistan_organiz_184fe9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiaction",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_assistan_user_id_8c35b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiaction",
            index=models.Index(
                fields=["action_type", "status"], name="ai_assistan_action__f7848d_idx"
            ),
        ),
    ]
