# Generated by Django 4.2.24 on 2025-11-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="feedback",
            field=models.CharField(
                blank=True,
                choices=[("positive", "Positive"), ("negative", "Negative")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="feedback_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="feedback_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["feedback", "-created_at"], name="ai_assistan_feedbac_9010f0_idx"
            ),
        ),
    ]
